apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    storsys: nfs
spec:
  storageClassName: nfs-sc
  accessModes: ["ReadWriteOnce","ReadOnlyMany","ReadWriteMany"]
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.52.133
    path: /tmp/nfs/data