apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: CUSTOM_TEST
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: test
        - name: CUSTOM_NAME
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: name
      envFrom:
        - configMapRef:
            name: env-cm
  restartPolicy: Never